### ISSUE TITLE
love it but

### ISSUE THREAD

**Issue by Hacks-lol** [ThatFruedDued/kahoot-smasher#1]
we need a way to, auto answer, and also the quizzs thing do you think it will ever work again

**Comment by ThatFruedDued** [comment]
The bots already automatically answer random answers. If you are speaking of automatic correct answers, this is impossible because of the way Kahoot works. The Quizizz script may work again in the future, but the answer fetching would only work for public Quizizzes, and I am not currently working on that script.

Did I answer your questions?

**Comment by Hacks-lol** [comment]
Yes thanks! :]
